### PR TITLE
Java8 provenance

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by morgantaschuk** [comment]
Test fails, but it also fails on develop so maybe an underlying problem?

```
niassa$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
niassa$ mvn -B -q clean install
...
...
Created IUS[limsKeySwid=1] with SWID: 2
Created LimsKey[seqware,1,426e0b848d77d7b3d778187d006056ee406221ca567ce2844ca403dc834ff8f1,2017-01-01T01:01:01Z] with SWID: 3
Created IUS[limsKeySwid=3] with SWID: 4
Added 'WorkflowName' (SWID: 1)
Created workflow run with SWID: 6
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.137 s <<< FAILURE! - in io.seqware.pipeline.engines.whitestar.PersistenceTest
[ERROR] testReadWorkflowRun(io.seqware.pipeline.engines.whitestar.PersistenceTest)  Time elapsed: 0.078 s  <<< ERROR!
java.lang.RuntimeException: Missing SW_METADATA_METHOD entry in seqware settings.
	at io.seqware.pipeline.engines.whitestar.PersistenceTest.testReadWorkflowRun(PersistenceTest.java:55)

[ERROR] Errors: 
[ERROR]   PersistenceTest.testReadWorkflowRun:55 » Runtime Missing SW_METADATA_METHOD en...
[ERROR] Tests run: 46, Failures: 0, Errors: 1, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project seqware-pipeline: There are test failures.
```

**Comment by apmasell** [comment]
I have no idea on that one. I've not seen an error like that. My `~/.seqware/settings` has `SW_METADATA_METHOD=webservice`, but it shouldn't be reading that for testing, right?

**Comment by morgantaschuk** [comment]
I don't have a ~/.seqware/settings... let me create one

**Comment by morgantaschuk** [comment]
Build success when I have a ~/.seqware/settings file! Welp that's uncool.

**Pull request merged**
