### PR TITLE
Plugin to re-run an existing workflow run

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by apmasell** [comment]
retest this please

**Comment by apmasell** [comment]
Okay. I've added the test. The test passed, but Jenkins died trying to talk to Artifactory, so it looks failed. :disappointed:

**Pull request merged**
